apiVersion: apps/v1
kind: Deployment
metadata:
  name: swr-performance-test-push-int
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swr-performance-test-push-int
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: swr-performance-test-push-int
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9101"
        prometheus.io/scheme: http
    spec:
      containers:
      - name: swr-push-int
        image: swr.eu-de.otc.t-systems.com/container/swr-performance-test:push-int3
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
          - /bin/sh
          - '-c'
        args:
          - /exporter.sh
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: swr-secret
              key: username
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: swr-secret
              key: password
        resources:
          requests:
            cpu: "0.5"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: containerd-sock
          mountPath: /run/containerd/containerd.sock
          readOnly: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - test $(expr $(date +%s) - $(cat /tmp/heartbeat)) -lt 60
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: swr-performance-test-pvc
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: default-secret

