apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swr-pvc
  namespace: default
  annotations:
    everest.io/obs-volume-type: STANDARD
    csi.storage.k8s.io/fstype: obsfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-obs
